"""add geometry waypoints to routes

Revision ID: 4db9b41c68ea
Revises: ac6e6dec4b03
Create Date: 2026-02-26 19:48:02.304898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4db9b41c68ea'
down_revision: Union[str, None] = 'ac6e6dec4b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trail_routes', sa.Column('end_lat', sa.Float(), nullable=True))
    op.add_column('trail_routes', sa.Column('end_lng', sa.Float(), nullable=True))
    op.add_column('trail_routes', sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('trail_routes', sa.Column('waypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trail_routes', 'waypoints')
    op.drop_column('trail_routes', 'geometry')
    op.drop_column('trail_routes', 'end_lng')
    op.drop_column('trail_routes', 'end_lat')
    # ### end Alembic commands ###
