"""make route coordinates required

Revision ID: 4f40e2bfc523
Revises: ab852f9a24cd
Create Date: 2026-03-02 11:52:02.264102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f40e2bfc523'
down_revision: Union[str, None] = 'ab852f9a24cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Delete routes with NULL coordinates (they'd violate NOT NULL)
    op.execute(
        "DELETE FROM trail_routes WHERE start_lat IS NULL OR start_lng IS NULL "
        "OR end_lat IS NULL OR end_lng IS NULL OR geometry IS NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trail_routes', 'start_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trail_routes', 'start_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trail_routes', 'end_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trail_routes', 'end_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trail_routes', 'geometry',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trail_routes', 'geometry',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('trail_routes', 'end_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trail_routes', 'end_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trail_routes', 'start_lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trail_routes', 'start_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
