"""add paid routes and subscriptions

Revision ID: 997c496c95fd
Revises: a1b2c3d4e5f6
Create Date: 2026-03-24 10:14:27.121480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997c496c95fd'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscriptionstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_subscriptions_creator_id'), 'creator_subscriptions', ['creator_id'], unique=False)
    op.create_index(op.f('ix_creator_subscriptions_status'), 'creator_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_creator_subscriptions_subscriber_id'), 'creator_subscriptions', ['subscriber_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_creator_id'), 'subscription_plans', ['creator_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'cancelled', name='paymentstatus'), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=100), nullable=True),
    sa.Column('confirmation_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['creator_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yookassa_payment_id')
    )
    op.create_index(op.f('ix_payments_creator_id'), 'payments', ['creator_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.add_column('trail_routes', sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('trail_routes', sa.Column('preview_description', sa.Text(), nullable=True))
    op.drop_index('ix_trail_routes_fts', table_name='trail_routes', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trail_routes_fts', 'trail_routes', [sa.text("to_tsvector('russian'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_column('trail_routes', 'preview_description')
    op.drop_column('trail_routes', 'is_paid')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_creator_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_subscription_plans_creator_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_creator_subscriptions_subscriber_id'), table_name='creator_subscriptions')
    op.drop_index(op.f('ix_creator_subscriptions_status'), table_name='creator_subscriptions')
    op.drop_index(op.f('ix_creator_subscriptions_creator_id'), table_name='creator_subscriptions')
    op.drop_table('creator_subscriptions')
    # ### end Alembic commands ###
