"""add yookassa_account_id to subscription_plans

Revision ID: b45c4476abc4
Revises: 997c496c95fd
Create Date: 2026-03-24 11:17:59.627975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45c4476abc4'
down_revision: Union[str, None] = '997c496c95fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('yookassa_account_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'yookassa_account_id')
    # ### end Alembic commands ###
